// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_gog.Data;

#nullable disable

namespace mvcgog.Migrations
{
    [DbContext(typeof(mvc_gogContext))]
    [Migration("20240910150520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mvc_gog.Models.LigneBackup", b =>
                {
                    b.Property<int>("LigneBackupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LignePanierID")
                        .HasColumnType("int");

                    b.Property<int>("NbreArticle")
                        .HasColumnType("int");

                    b.Property<int>("PanierID")
                        .HasColumnType("int");

                    b.Property<string>("Prodname")
                        .HasColumnType("longtext");

                    b.Property<int>("ProduitID")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("LigneBackupID");

                    b.ToTable("LigneBackup");
                });

            modelBuilder.Entity("mvc_gog.Models.LignePanier", b =>
                {
                    b.Property<int>("LignePanierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NbreArticle")
                        .HasColumnType("int");

                    b.Property<int>("PanierID")
                        .HasColumnType("int");

                    b.Property<int>("ProduitID")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("LignePanierID");

                    b.HasIndex("PanierID");

                    b.HasIndex("ProduitID");

                    b.ToTable("LignePanier");
                });

            modelBuilder.Entity("mvc_gog.Models.Panier", b =>
                {
                    b.Property<int>("PanierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NbreArticle")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PanierID");

                    b.HasIndex("UserID");

                    b.ToTable("Panier");
                });

            modelBuilder.Entity("mvc_gog.Models.Produit", b =>
                {
                    b.Property<int>("ProduitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Dateofcreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PanierID")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Prodname")
                        .HasColumnType("longtext");

                    b.Property<string>("desc")
                        .HasColumnType("longtext");

                    b.Property<string>("imageurl")
                        .HasColumnType("longtext");

                    b.HasKey("ProduitID");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("mvc_gog.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("mvc_gog.Models.LignePanier", b =>
                {
                    b.HasOne("mvc_gog.Models.Panier", null)
                        .WithMany("LignePanier")
                        .HasForeignKey("PanierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvc_gog.Models.Produit", "produit")
                        .WithMany()
                        .HasForeignKey("ProduitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("produit");
                });

            modelBuilder.Entity("mvc_gog.Models.Panier", b =>
                {
                    b.HasOne("mvc_gog.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("mvc_gog.Models.Panier", b =>
                {
                    b.Navigation("LignePanier");
                });
#pragma warning restore 612, 618
        }
    }
}
